//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Tabl_chast8
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Родитель.
    /// </summary>
    // *** Start programmer edit section *** (Родитель CustomAttributes)

    // *** End programmer edit section *** (Родитель CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("РодительE", new string[] {
            "Фио as \'Фио\'"})]
    [View("РодительL", new string[] {
            "Фио as \'Фио\'"})]
    public class Родитель : ICSSoft.STORMNET.DataObject
    {
        
        private string fФио;
        
        // *** Start programmer edit section *** (Родитель CustomMembers)

        // *** End programmer edit section *** (Родитель CustomMembers)

        
        /// <summary>
        /// Фио.
        /// </summary>
        // *** Start programmer edit section *** (Родитель.Фио CustomAttributes)

        // *** End programmer edit section *** (Родитель.Фио CustomAttributes)
        [StrLen(255)]
        public virtual string Фио
        {
            get
            {
                // *** Start programmer edit section *** (Родитель.Фио Get start)

                // *** End programmer edit section *** (Родитель.Фио Get start)
                string result = this.fФио;
                // *** Start programmer edit section *** (Родитель.Фио Get end)

                // *** End programmer edit section *** (Родитель.Фио Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Родитель.Фио Set start)

                // *** End programmer edit section *** (Родитель.Фио Set start)
                this.fФио = value;
                // *** Start programmer edit section *** (Родитель.Фио Set end)

                // *** End programmer edit section *** (Родитель.Фио Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "РодительE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РодительE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РодительE", typeof(IIS.Tabl_chast8.Родитель));
                }
            }
            
            /// <summary>
            /// "РодительL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РодительL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РодительL", typeof(IIS.Tabl_chast8.Родитель));
                }
            }
        }
    }
}
