//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Tabl_chast8
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// СтатусУч.
    /// </summary>
    // *** Start programmer edit section *** (СтатусУч CustomAttributes)

    // *** End programmer edit section *** (СтатусУч CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СтатусУчE", new string[] {
            "Назв as \'Назв\'"})]
    [View("СтатусУчL", new string[] {
            "Назв as \'Назв\'"})]
    public class СтатусУч : ICSSoft.STORMNET.DataObject
    {
        
        private string fНазв;
        
        // *** Start programmer edit section *** (СтатусУч CustomMembers)

        // *** End programmer edit section *** (СтатусУч CustomMembers)

        
        /// <summary>
        /// Назв.
        /// </summary>
        // *** Start programmer edit section *** (СтатусУч.Назв CustomAttributes)

        // *** End programmer edit section *** (СтатусУч.Назв CustomAttributes)
        [StrLen(255)]
        public virtual string Назв
        {
            get
            {
                // *** Start programmer edit section *** (СтатусУч.Назв Get start)

                // *** End programmer edit section *** (СтатусУч.Назв Get start)
                string result = this.fНазв;
                // *** Start programmer edit section *** (СтатусУч.Назв Get end)

                // *** End programmer edit section *** (СтатусУч.Назв Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СтатусУч.Назв Set start)

                // *** End programmer edit section *** (СтатусУч.Назв Set start)
                this.fНазв = value;
                // *** Start programmer edit section *** (СтатусУч.Назв Set end)

                // *** End programmer edit section *** (СтатусУч.Назв Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СтатусУчE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СтатусУчE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СтатусУчE", typeof(IIS.Tabl_chast8.СтатусУч));
                }
            }
            
            /// <summary>
            /// "СтатусУчL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СтатусУчL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СтатусУчL", typeof(IIS.Tabl_chast8.СтатусУч));
                }
            }
        }
    }
}
