//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Tabl_chast8
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Учитель.
    /// </summary>
    // *** Start programmer edit section *** (Учитель CustomAttributes)

    // *** End programmer edit section *** (Учитель CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("УчительE", new string[] {
            "Фио as \'Фио\'"})]
    public class Учитель : ICSSoft.STORMNET.DataObject
    {
        
        private string fФио;
        
        private IIS.Tabl_chast8.Школа fШкола;
        
        // *** Start programmer edit section *** (Учитель CustomMembers)

        // *** End programmer edit section *** (Учитель CustomMembers)

        
        /// <summary>
        /// Фио.
        /// </summary>
        // *** Start programmer edit section *** (Учитель.Фио CustomAttributes)

        // *** End programmer edit section *** (Учитель.Фио CustomAttributes)
        [StrLen(255)]
        public virtual string Фио
        {
            get
            {
                // *** Start programmer edit section *** (Учитель.Фио Get start)

                // *** End programmer edit section *** (Учитель.Фио Get start)
                string result = this.fФио;
                // *** Start programmer edit section *** (Учитель.Фио Get end)

                // *** End programmer edit section *** (Учитель.Фио Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Учитель.Фио Set start)

                // *** End programmer edit section *** (Учитель.Фио Set start)
                this.fФио = value;
                // *** Start programmer edit section *** (Учитель.Фио Set end)

                // *** End programmer edit section *** (Учитель.Фио Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Tabl_chast8.Школа.
        /// </summary>
        // *** Start programmer edit section *** (Учитель.Школа CustomAttributes)

        // *** End programmer edit section *** (Учитель.Школа CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Школа"})]
        public virtual IIS.Tabl_chast8.Школа Школа
        {
            get
            {
                // *** Start programmer edit section *** (Учитель.Школа Get start)

                // *** End programmer edit section *** (Учитель.Школа Get start)
                IIS.Tabl_chast8.Школа result = this.fШкола;
                // *** Start programmer edit section *** (Учитель.Школа Get end)

                // *** End programmer edit section *** (Учитель.Школа Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Учитель.Школа Set start)

                // *** End programmer edit section *** (Учитель.Школа Set start)
                this.fШкола = value;
                // *** Start programmer edit section *** (Учитель.Школа Set end)

                // *** End programmer edit section *** (Учитель.Школа Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "УчительE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View УчительE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("УчительE", typeof(IIS.Tabl_chast8.Учитель));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Учитель.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfУчитель CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfУчитель CustomAttributes)
    public class DetailArrayOfУчитель : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Tabl_chast8.DetailArrayOfУчитель members)

        // *** End programmer edit section *** (IIS.Tabl_chast8.DetailArrayOfУчитель members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Учитель by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Учитель.
        /// </summary>
        public DetailArrayOfУчитель(IIS.Tabl_chast8.Школа fШкола) : 
                base(typeof(Учитель), ((ICSSoft.STORMNET.DataObject)(fШкола)))
        {
        }
        
        public IIS.Tabl_chast8.Учитель this[int index]
        {
            get
            {
                return ((IIS.Tabl_chast8.Учитель)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Tabl_chast8.Учитель dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
