//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Tabl_chast8
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Ученик.
    /// </summary>
    // *** Start programmer edit section *** (Ученик CustomAttributes)

    // *** End programmer edit section *** (Ученик CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("УченикE", new string[] {
            "ФИО as \'ФИО\'",
            "КлассУч as \'Класс уч\'",
            "КлассУч.Назв as \'Назв\'",
            "СтатусУч as \'Статус уч\'",
            "СтатусУч.Назв as \'Назв\'",
            "Родитель as \'Родитель\'",
            "Родитель.Фио as \'Фио\'"}, Hidden=new string[] {
            "КлассУч.Назв",
            "СтатусУч.Назв",
            "Родитель.Фио"})]
    [MasterViewDefineAttribute("УченикE", "КлассУч", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Назв")]
    [MasterViewDefineAttribute("УченикE", "СтатусУч", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Назв")]
    [MasterViewDefineAttribute("УченикE", "Родитель", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Фио")]
    public class Ученик : ICSSoft.STORMNET.DataObject
    {
        
        private string fФИО;
        
        private IIS.Tabl_chast8.СтатусУч fСтатусУч;
        
        private IIS.Tabl_chast8.Родитель fРодитель;
        
        private IIS.Tabl_chast8.КлассУч fКлассУч;
        
        private IIS.Tabl_chast8.Школа fШкола;
        
        // *** Start programmer edit section *** (Ученик CustomMembers)

        // *** End programmer edit section *** (Ученик CustomMembers)

        
        /// <summary>
        /// ФИО.
        /// </summary>
        // *** Start programmer edit section *** (Ученик.ФИО CustomAttributes)

        // *** End programmer edit section *** (Ученик.ФИО CustomAttributes)
        [StrLen(255)]
        public virtual string ФИО
        {
            get
            {
                // *** Start programmer edit section *** (Ученик.ФИО Get start)

                // *** End programmer edit section *** (Ученик.ФИО Get start)
                string result = this.fФИО;
                // *** Start programmer edit section *** (Ученик.ФИО Get end)

                // *** End programmer edit section *** (Ученик.ФИО Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Ученик.ФИО Set start)

                // *** End programmer edit section *** (Ученик.ФИО Set start)
                this.fФИО = value;
                // *** Start programmer edit section *** (Ученик.ФИО Set end)

                // *** End programmer edit section *** (Ученик.ФИО Set end)
            }
        }
        
        /// <summary>
        /// Ученик.
        /// </summary>
        // *** Start programmer edit section *** (Ученик.КлассУч CustomAttributes)

        // *** End programmer edit section *** (Ученик.КлассУч CustomAttributes)
        [PropertyStorage(new string[] {
                "КлассУч"})]
        [NotNull()]
        public virtual IIS.Tabl_chast8.КлассУч КлассУч
        {
            get
            {
                // *** Start programmer edit section *** (Ученик.КлассУч Get start)

                // *** End programmer edit section *** (Ученик.КлассУч Get start)
                IIS.Tabl_chast8.КлассУч result = this.fКлассУч;
                // *** Start programmer edit section *** (Ученик.КлассУч Get end)

                // *** End programmer edit section *** (Ученик.КлассУч Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Ученик.КлассУч Set start)

                // *** End programmer edit section *** (Ученик.КлассУч Set start)
                this.fКлассУч = value;
                // *** Start programmer edit section *** (Ученик.КлассУч Set end)

                // *** End programmer edit section *** (Ученик.КлассУч Set end)
            }
        }
        
        /// <summary>
        /// Ученик.
        /// </summary>
        // *** Start programmer edit section *** (Ученик.Родитель CustomAttributes)

        // *** End programmer edit section *** (Ученик.Родитель CustomAttributes)
        [PropertyStorage(new string[] {
                "Родитель"})]
        [NotNull()]
        public virtual IIS.Tabl_chast8.Родитель Родитель
        {
            get
            {
                // *** Start programmer edit section *** (Ученик.Родитель Get start)

                // *** End programmer edit section *** (Ученик.Родитель Get start)
                IIS.Tabl_chast8.Родитель result = this.fРодитель;
                // *** Start programmer edit section *** (Ученик.Родитель Get end)

                // *** End programmer edit section *** (Ученик.Родитель Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Ученик.Родитель Set start)

                // *** End programmer edit section *** (Ученик.Родитель Set start)
                this.fРодитель = value;
                // *** Start programmer edit section *** (Ученик.Родитель Set end)

                // *** End programmer edit section *** (Ученик.Родитель Set end)
            }
        }
        
        /// <summary>
        /// Ученик.
        /// </summary>
        // *** Start programmer edit section *** (Ученик.СтатусУч CustomAttributes)

        // *** End programmer edit section *** (Ученик.СтатусУч CustomAttributes)
        [PropertyStorage(new string[] {
                "СтатусУч"})]
        [NotNull()]
        public virtual IIS.Tabl_chast8.СтатусУч СтатусУч
        {
            get
            {
                // *** Start programmer edit section *** (Ученик.СтатусУч Get start)

                // *** End programmer edit section *** (Ученик.СтатусУч Get start)
                IIS.Tabl_chast8.СтатусУч result = this.fСтатусУч;
                // *** Start programmer edit section *** (Ученик.СтатусУч Get end)

                // *** End programmer edit section *** (Ученик.СтатусУч Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Ученик.СтатусУч Set start)

                // *** End programmer edit section *** (Ученик.СтатусУч Set start)
                this.fСтатусУч = value;
                // *** Start programmer edit section *** (Ученик.СтатусУч Set end)

                // *** End programmer edit section *** (Ученик.СтатусУч Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Tabl_chast8.Школа.
        /// </summary>
        // *** Start programmer edit section *** (Ученик.Школа CustomAttributes)

        // *** End programmer edit section *** (Ученик.Школа CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Школа"})]
        public virtual IIS.Tabl_chast8.Школа Школа
        {
            get
            {
                // *** Start programmer edit section *** (Ученик.Школа Get start)

                // *** End programmer edit section *** (Ученик.Школа Get start)
                IIS.Tabl_chast8.Школа result = this.fШкола;
                // *** Start programmer edit section *** (Ученик.Школа Get end)

                // *** End programmer edit section *** (Ученик.Школа Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Ученик.Школа Set start)

                // *** End programmer edit section *** (Ученик.Школа Set start)
                this.fШкола = value;
                // *** Start programmer edit section *** (Ученик.Школа Set end)

                // *** End programmer edit section *** (Ученик.Школа Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "УченикE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View УченикE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("УченикE", typeof(IIS.Tabl_chast8.Ученик));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Ученик.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfУченик CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfУченик CustomAttributes)
    public class DetailArrayOfУченик : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Tabl_chast8.DetailArrayOfУченик members)

        // *** End programmer edit section *** (IIS.Tabl_chast8.DetailArrayOfУченик members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Ученик by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Ученик.
        /// </summary>
        public DetailArrayOfУченик(IIS.Tabl_chast8.Школа fШкола) : 
                base(typeof(Ученик), ((ICSSoft.STORMNET.DataObject)(fШкола)))
        {
        }
        
        public IIS.Tabl_chast8.Ученик this[int index]
        {
            get
            {
                return ((IIS.Tabl_chast8.Ученик)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Tabl_chast8.Ученик dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
