//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Tabl_chast8
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Школа.
    /// </summary>
    // *** Start programmer edit section *** (Школа CustomAttributes)

    // *** End programmer edit section *** (Школа CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ШколаE", new string[] {
            "Назв as \'Назв\'"})]
    [AssociatedDetailViewAttribute("ШколаE", "Ученик", "УченикE", true, "", "Ученик", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("ШколаE", "Учитель", "УчительE", true, "", "Учитель", true, new string[] {
            ""})]
    [View("ШколаL", new string[] {
            "Назв as \'Назв\'"})]
    public class Школа : ICSSoft.STORMNET.DataObject
    {
        
        private string fНазв;
        
        private IIS.Tabl_chast8.DetailArrayOfУченик fУченик;
        
        private IIS.Tabl_chast8.DetailArrayOfУчитель fУчитель;
        
        // *** Start programmer edit section *** (Школа CustomMembers)

        // *** End programmer edit section *** (Школа CustomMembers)

        
        /// <summary>
        /// Назв.
        /// </summary>
        // *** Start programmer edit section *** (Школа.Назв CustomAttributes)

        // *** End programmer edit section *** (Школа.Назв CustomAttributes)
        [StrLen(255)]
        public virtual string Назв
        {
            get
            {
                // *** Start programmer edit section *** (Школа.Назв Get start)

                // *** End programmer edit section *** (Школа.Назв Get start)
                string result = this.fНазв;
                // *** Start programmer edit section *** (Школа.Назв Get end)

                // *** End programmer edit section *** (Школа.Назв Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Школа.Назв Set start)

                // *** End programmer edit section *** (Школа.Назв Set start)
                this.fНазв = value;
                // *** Start programmer edit section *** (Школа.Назв Set end)

                // *** End programmer edit section *** (Школа.Назв Set end)
            }
        }
        
        /// <summary>
        /// Школа.
        /// </summary>
        // *** Start programmer edit section *** (Школа.Ученик CustomAttributes)

        // *** End programmer edit section *** (Школа.Ученик CustomAttributes)
        public virtual IIS.Tabl_chast8.DetailArrayOfУченик Ученик
        {
            get
            {
                // *** Start programmer edit section *** (Школа.Ученик Get start)

                // *** End programmer edit section *** (Школа.Ученик Get start)
                if ((this.fУченик == null))
                {
                    this.fУченик = new IIS.Tabl_chast8.DetailArrayOfУченик(this);
                }
                IIS.Tabl_chast8.DetailArrayOfУченик result = this.fУченик;
                // *** Start programmer edit section *** (Школа.Ученик Get end)

                // *** End programmer edit section *** (Школа.Ученик Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Школа.Ученик Set start)

                // *** End programmer edit section *** (Школа.Ученик Set start)
                this.fУченик = value;
                // *** Start programmer edit section *** (Школа.Ученик Set end)

                // *** End programmer edit section *** (Школа.Ученик Set end)
            }
        }
        
        /// <summary>
        /// Школа.
        /// </summary>
        // *** Start programmer edit section *** (Школа.Учитель CustomAttributes)

        // *** End programmer edit section *** (Школа.Учитель CustomAttributes)
        public virtual IIS.Tabl_chast8.DetailArrayOfУчитель Учитель
        {
            get
            {
                // *** Start programmer edit section *** (Школа.Учитель Get start)

                // *** End programmer edit section *** (Школа.Учитель Get start)
                if ((this.fУчитель == null))
                {
                    this.fУчитель = new IIS.Tabl_chast8.DetailArrayOfУчитель(this);
                }
                IIS.Tabl_chast8.DetailArrayOfУчитель result = this.fУчитель;
                // *** Start programmer edit section *** (Школа.Учитель Get end)

                // *** End programmer edit section *** (Школа.Учитель Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Школа.Учитель Set start)

                // *** End programmer edit section *** (Школа.Учитель Set start)
                this.fУчитель = value;
                // *** Start programmer edit section *** (Школа.Учитель Set end)

                // *** End programmer edit section *** (Школа.Учитель Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ШколаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ШколаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ШколаE", typeof(IIS.Tabl_chast8.Школа));
                }
            }
            
            /// <summary>
            /// "ШколаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ШколаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ШколаL", typeof(IIS.Tabl_chast8.Школа));
                }
            }
        }
    }
}
